### ISSUE TITLE
method destroy return callback error

### ISSUE THREAD

**Issue by perciag** [vjsrinath/sails-orientdb#3]
I had been this king of error when I try to run the method : destroy of the file connection.js. Do you have any idea what can be wrong?

Possibly unhandled TypeError: undefined is not a function
    at null.<anonymous> (/Users/percival/projetos/mySleep/node_modules/sails-orientdb/lib/connection.js:366:17)
    at process._tickDomainCallback (node.js:463:13)
From previous event:
    at Promise$catch (/Users/percival/projetos/mySleep/node_modules/sails-orientdb/node_modules/oriento/node_modules/bluebird/js/main/promise.js:131:14)
    at module.exports.dbHelper.destroy (/Users/percival/projetos/mySleep/node_modules/sails-orientdb/lib/connection.js:367:16)
    at Object.module.exports.adapter.destroy (/Users/percival/projetos/mySleep/node_modules/sails-orientdb/lib/adapter.js:204:44)
    at module.exports.destroy (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:268:13)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/destroy.js:55:18
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:157:25
    at null.<anonymous> (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44)

**Comment by vjsrinath** [comment]
Hi, Thanks for reporting the issue. It has been fixed and latest version pushed to NPM
